<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150517/1-15051H23037.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150517/1-15051H23037.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="700";
$z[1][4]['height']="525";
$z[2]=Array("img"," /uploads/allimg/150517/1-15051H23039.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/150517/1-15051H23039.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="700";
$z[2][4]['height']="525";
$z[3]=Array("img"," /uploads/allimg/150517/1-15051H23046.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/150517/1-15051H23046.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="700";
$z[3][4]['height']="525";
$z[4]=Array("img"," /uploads/allimg/150517/1-15051H23048.jpg ",534,679);
$z[4][4]['ddimg']="/uploads/allimg/150517/1-15051H23048.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="700";
$z[4][4]['height']="525";
$z[5]=Array("img"," /uploads/allimg/150517/1-15051H23051.jpg ",681,826);
$z[5][4]['ddimg']="/uploads/allimg/150517/1-15051H23051.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="700";
$z[5][4]['height']="525";

?>