<li class="item" data-thumb="[field:imgsrc/]" style="background-image: url([field:imgsrc/])">
                                   <div class="container"> <a href="[field:imgsrc/]" rel="prettyPhoto[gal]"></a>
                                        <div class="carousel-caption">
                                             <p class="lead">[field:text/]</p>
                                        </div>
                                   </div>
                              </li>