<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150517/1-15051H04405.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150517/1-15051H04405.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="750";
$z[1][4]['height']="500";
$z[2]=Array("img"," /uploads/allimg/150517/1-15051H04409.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/150517/1-15051H04409.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="750";
$z[2][4]['height']="500";
$z[3]=Array("img"," /uploads/allimg/150517/1-15051H04412.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/150517/1-15051H04412.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="750";
$z[3][4]['height']="492";
$z[4]=Array("img"," /uploads/allimg/150517/1-15051H04415.jpg ",534,681);
$z[4][4]['ddimg']="/uploads/allimg/150517/1-15051H04415.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1600";
$z[4][4]['height']="1060";

?>