<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150517/1-15051H14438.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/150517/1-15051H14438.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="682";
$z[2]=Array("img"," /uploads/allimg/150517/1-15051H14442.jpg ",241,387);
$z[2][4]['ddimg']="/uploads/allimg/150517/1-15051H14442.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1024";
$z[2][4]['height']="682";
$z[3]=Array("img"," /uploads/allimg/150517/1-15051H14447.jpg ",389,535);
$z[3][4]['ddimg']="/uploads/allimg/150517/1-15051H14447.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="900";
$z[4]=Array("img"," /uploads/allimg/150517/1-15051H14451.jpg ",537,683);
$z[4][4]['ddimg']="/uploads/allimg/150517/1-15051H14451.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1024";
$z[4][4]['height']="768";

?>