<div class="portfolio_item span3">
                         <div class="portfolio_photo" style="background-image:url(/style/images/portfolio/a1.jpg)"> <a href="portfolio_item.html"> <i class="icon-2x icon-external-link"></i>
                              <p>[field:title/]</p>
                              </a> </div>
                         <div class="portfolio_description">
                              <h3><a href="portfolio_item.html">[field:title/]</a></h3>
                             
                         </div>
                    </div>