<div class="portfolio_item span3">
                         <div class="portfolio_photo" style="background-image:url([field:litpic/])"> <a href="[field:arcurl/]"> <i class="icon-2x icon-external-link"></i>
                          
                              </a> </div>
                         <div class="portfolio_description">
                              <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                             
                         </div>
                    </div>