<div class="portfolio_item span3">
                         <div class="portfolio_photo" style="background-image:url([field:litpic/])"> <a href="[field:arcurl/]"> <i class="icon-2x icon-external-link"></i>
                              <p>[field:title/]</p>
                              </a> </div>
                         <div class="portfolio_description">
                        
                             
                         </div>
                    </div>