<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",321,348);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",388,418);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",516,548);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",612,644);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",699,731);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",825,857);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",941,973);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1051,1083);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("include","",1294,1329);
$z[9][4]['filename']="head.htm";
$z[10]=Array("arclist","\r\n					<dd><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></dd>\r\n					",5746,5900);
$z[10][4]['typeid']="2";
$z[10][4]['row']="7";
$z[11]=Array("arclist","\r\n				<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[[field:pubdate function='strftime(\"%y-%m-%d\",@me)'/]] &nbsp; [field:title/]</a></li>\r\n				",8029,8244);
$z[11][4]['typeid']="2";
$z[11][4]['row']="11";
$z[12]=Array("arclist","\r\n				<li><div class=\"case_pic\"><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" width=\"241\" height=\"145\" alt=\"[field:title/]\"  /></a></div><div class=\"case_name\"><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></div></li>\r\n            	",8718,9082);
$z[12][4]['typeid']="2";
$z[12][4]['row']="11";
$z[13]=Array("channelartlist","\r\n                <li>\r\n            	<h2 class=\"art_title\"><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></h2>\r\n                	<ol class=\"arc_sublist\">\r\n						{dede:arclist titlelen='60' row='5'}\r\n						<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[[field:pubdate function='strftime(\"%y-%m-%d\",@me)'/]] [field:title/]</a></li>\r\n						{/dede:arclist}\r\n					</ol>\r\n                <a href=\"{dede:field name='typeurl'/}\" class=\"arc_more\">还有&gt;&gt;</a>\r\n            </li>\r\n			",9620,10242);
$z[13][4]['typeid']="10";
$z[14]=Array("include","",10400,10437);
$z[14][4]['filename']="footer.htm";

?>