<?php
$z[0]=Array("global","",361,387);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",428,455);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",495,525);
$z[2][4]['name']="cfg_description";
$z[3]=Array("channel","\r\n							  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n							        ",2696,2907);
$z[3][4]['type']="top";
$z[3][4]['row']="4";
$z[3][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a> </li>";
$z[4]=Array("arclist","\r\n               <li class=\"item\" style=\"background-image: url([field:litpic/])\">\r\n                    <div class=\"container\">\r\n                         <div class=\"carousel-caption\">\r\n                              <h1>[field:title/]</h1>                \r\n                             \r\n                             \r\n                    </div>\r\n               </li>\r\n			",3178,3615);
$z[4][4]['row']="15";
$z[4][4]['typeid']="4";
$z[4][4]['orderby']="rand";
$z[5]=Array("arclist","\r\n                    <div class=\"portfolio_item span3\">\r\n                         <div class=\"portfolio_photo\" style=\"background-image:url([field:litpic/])\"> <a href=\"[field:arcurl/]\"> <i class=\"icon-2x icon-external-link\"></i>\r\n                          \r\n                              </a> </div>\r\n                         <div class=\"portfolio_description\">\r\n                              <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                             \r\n                         </div>\r\n                    </div>\r\n				",3844,4452);
$z[5][4]['row']="4";
$z[5][4]['typeid']="1";
$z[5][4]['orderby']="rand";
$z[6]=Array("include","",4538,4575);
$z[6][4]['filename']="footer.htm";

?>