<?php
$z[0]=Array("field","",363,392);
$z[0][4]['name']="typename";
$z[1]=Array("global","",395,421);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",462,491);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",529,587);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2013,2048);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2185,2213);
$z[5][4]['name']="content";
$z[6]=Array("field","",2290,2319);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n				<div class=\"portfolio_item cat_projects span4\"> \r\n					<a href=\"[field:arcurl/]\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\" />\r\n						<div class=\"overlay\">\r\n							 <div class=\"desc\"> <i class=\"icon-2x icon-external-link\"></i>\r\n								  <h3>[field:title/]</h3>\r\n							 </div>\r\n						</div>\r\n                    </a> \r\n				</div>\r\n			",2438,2836);
$z[7][4]['pagesize']="9";
$z[7][4]['orderby']="rand";
$z[8]=Array("include","",2870,2908);
$z[8][4]['filename']="footer2.htm";

?>