<?php
$z[0]=Array("field","",361,390);
$z[0][4]['name']="typename";
$z[1]=Array("global","",393,419);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",460,489);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",527,585);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2015,2050);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2213,2241);
$z[5][4]['name']="content";
$z[6]=Array("field","",2318,2347);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n                <div class=\"portfolio_item cat_artists span4\">\r\n                    <div class=\"portfolio_photo\" style=\"background-image:url([field:litpic/])\"> <a href=\"[field:arcurl/]\"> <i class=\"icon-2x icon-external-link\"></i>\r\n                         <p>[field:jj/]</p> \r\n                         </a> </div>\r\n                    <div class=\"portfolio_description\">\r\n                         <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                    </div>\r\n               </div>\r\n			",2464,3024);
$z[7][4]['pagesize']="9";
$z[7][4]['orderby']="rand";
$z[8]=Array("include","",3087,3125);
$z[8][4]['filename']="footer2.htm";

?>